name: github pages preview

on:
  push:
    branches-ignore:
      - '**'
    tags:
      - 'v*.*.*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v3
        with:
          node-version: '20'

      # Cache for the node_modules
      - uses: actions/cache@v2
        id: cache-docs-npm
        with:
          path: node_modules
          key: ${{ runner.os }}-docs-${{ hashFiles('./package-lock.json') }}

      - name: Install npm dependencies
        if: steps.cache-docs-npm.outputs.cache-hit != 'true'
        run: npm ci

      - name: Build the project
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
